#!/usr/bin/env bash
#
# sync-consumers.sh -- populate the gitignored /consumers/ landing dir with
# copies of our own nginx modules, so the harness can be pointed at them.
#
# WHY THIS EXISTS
#   The consumer-wiring exercise (memory/labs/nginx-module-testkit/
#   plan-wire-own-modules.md) measures what this tool finds when aimed at ten
#   real modules instead of the deliberately-minimal t/module. The instruction
#   behind it is explicit: do NOT fix the modules and do NOT commit the copies.
#   So the copies are a fixture -- disposable, regenerable, never a source of
#   truth. This script is how they are regenerated.
#
#   Copies rather than symlinks, deliberately: a build writes objects and a
#   .so next to the sources, and with symlinks that output would land inside
#   the module's REAL checkout. Copying keeps the exercise from touching the
#   repos it is measuring, which is the whole constraint.
#
# USAGE
#   tools/sync-consumers.sh [--dry-run] [--only <name>]
#
#   --dry-run     list what would be copied, copy nothing
#   --only NAME   sync a single consumer (directory name under consumers/,
#                 e.g. nginx-http-shield-module)
#
# INPUTS   the checkouts listed in TARGETS below, under /opt/myguard
# OUTPUTS  consumers/<name>/ inside this repo -- gitignored (.gitignore:20)
#
# SIDE EFFECTS
#   Writes only under consumers/. rsync --delete is NOT used: a stale file in a
#   consumer copy is harmless, whereas --delete plus a mistyped path is not.
#   To start clean, remove the directory yourself.
#   No network. No sudo. Never writes to the source checkouts.
#
# WHAT IS EXCLUDED, AND WHY
#   .git/     the copy is not a checkout; it must not look like one
#   .build/   per-module build output, regenerated by the module's own tooling
#   fuzz/     fuzz corpora (211M in label-autoconf alone) -- thousands of tiny
#             inputs for a different tool than this one
#   *.o *.so  stale artifacts; a stale .so silently fakes a probe result, which
#             this repo has been bitten by before
#             ([[feedback-stale-so-fakes-negative-control]])
#
# LIMITS / WHERE TO EXTEND
#   TARGETS is a hardcoded list because the set is a deliberate scope decision
#   (our own labs modules plus coraza-nginx), not "every module on the box" --
#   see the plan for the distinction. Adding a module means adding a row here
#   AND a row in the plan's results table.
#
set -euo pipefail

cd "$(dirname "$0")/.."

SUPER=/opt/myguard

# checkout path under $SUPER -- owner split is by git remote, not by name
TARGETS=(
    labs/nginx-api-abuse-module
    labs/nginx-autocert-module
    labs/nginx-cache-turbo-module
    labs/nginx-error-abuse-module
    # nginx-http-sentinel-module is DELIBERATELY ABSENT, not forgotten. It does
    # not compile against nginx 1.29.0: src/sentinel_pow.c:221 calls
    # ngx_http_parse_cookie_lines, which exists in no nginx core release (core
    # has ngx_http_parse_set_cookie_lines, a different function with a
    # different signature). That is a bug in the module, filed in its own
    # memory mirror -- this repo does not fix consumers, it reports on them.
    # Re-add the row once that module builds; syncing it before then only
    # copies 30M of sources that can never produce a .so.
    labs/nginx-http-shield-module
    labs/nginx-label-autoconf-module
    labs/nginx-skeleton-module
    labs/nginx-strip-filter-module
    eilandert/coraza-nginx
)

dry=0
only=""

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) dry=1 ;;
        --only)    only="${2:-}"; shift ;;
        *)         echo "unknown argument: $1" >&2; exit 2 ;;
    esac
    shift
done

for t in "${TARGETS[@]}"; do
    name=$(basename "$t")
    src="$SUPER/$t"

    if [ -n "$only" ] && [ "$name" != "$only" ]; then
        continue
    fi

    # A missing checkout is a real finding (the module moved, or was never
    # cloned), not something to paper over with a silent skip.
    if [ ! -d "$src" ]; then
        echo "MISSING  $t -- no such checkout" >&2
        continue
    fi

    if [ ! -f "$src/config" ]; then
        echo "WARNING  $t has no ./config -- it will not build as an addon" >&2
    fi

    if [ "$dry" = 1 ]; then
        echo "would sync $src -> consumers/$name/"
        continue
    fi

    mkdir -p "consumers/$name"
    rsync -a \
        --exclude '.git' \
        --exclude '.build/' \
        --exclude 'fuzz/' \
        --exclude '*.o' \
        --exclude '*.so' \
        "$src/" "consumers/$name/"

    echo "synced   $name"
done
